SPECIAL_MOVIE_NAMES = {
        # PUBLIC(-ALPHA)  ACTION
        "2012 Zombie Apocalypse": "Zombie Apocalypse",
        "310 to Yuma": "3:10 to Yuma",
        "Spy Kids 3D Game Over": "Spy Kids 3-D: Game Over",
        "AVP Alien vs Predator": "Alien vs Predator",
        "Assault on Precint 13": "Assault on Precinct 13",
        "Bad Boys 2": "Bad Boys II",
        "Brooklyns Finest": "Brooklyn's Finest",
        "Cowboys And Aliens": "Cowboys & Aliens",
        "Cradle to the Grave": "Cradle 2 the Grave",
        "Die Hard 2 Die Harder": "Die Hard 2",
        "Golden Killah": "Golden Mask",
        "Highlander End Game": "Highlander: Endgame",
        "Inferno": "Inferno",
        "Jackie Chans The Myth": "The Myth",
        "Kill Bill Volume 1": "Kill Bill: Vol. 1",
        "Kill Bill Volume 2": "Kill Bill: Vol. 2",
        "Mission Impossible 2 MI2": "Mission: Impossible II",
        "Mission Impossible 3": "Mission Impossible III",
        "Movie about the Seige": "The Siege",
        "Mr and Mrs Smith": "Mr. & Mrs. Smith",
        "Rambo 3": "Rambo III",
        "Rambo First Blood Part 2": "Rambo First Blood Part II",
        "Smoke Jumper": "Trial by Fire",
        "Spy Kids 2 The Island of Lost Dreams": "Spy Kids 2: Island of Lost Dreams",
        "Terminator 2 Judgement Day": "Terminator 2: Judgment Day",
        "The Fast and the Furious Tokyo Drift": "Tokyo Drift",
        "The Last Samuri": "The Last Samurai",
        "Under Seige": "Under Siege",

        # PUBLIC(-ALPHA)  ADVENTURE
        "A Bend of the River": "Bend of the River",
        "Bandit Bandits Silver Angel": "Bandit: Bandit's Silver Angel",
        "Beneath the 12 Mile Reef": "Beneath the 12-Mile Reef",
        "Charlies Angels": "Charlie's Angels",
        "Fools Gold": "Fool's Gold",
        "Get Smarts Bruce and Lloyd Out of Control": "Get Smart's Bruce and Lloyd Out of Control",
        "Harold and Kumar Escape from Guantanamo Bay": "Harold & Kumar Escape from Guantanamo Bay",
        "Harold and Kumar go to White Castle": "Harold & Kumar go to White Castle",
        "James Bond Golden Eye": "James Bond: Goldeneye",
        "National Treasure 2 Book of Secrets": "National Treasure: Book of Secrets",
        "Nims Island": "Nim's Island",
        "Pirates of the Caribbean At Worlds End": "Pirates of the Caribbean: At World's End",
        "SWAT": "S.W.A.T.",
        "Scooby Doo 2 Monsters Unleashed": "Scooby-Doo 2: Monsters Unleashed",
        "Smokey and the Bandit 2": "Smokey and the Bandit II",
        "The Adventures of Rocky and Bullwinkle": "The Adventures of Rocky & Bullwinkle",
        "The Hunger Games Mockinjay Part 2": "The Hunger Games: Mockingjay - Part 2",
        "The Man from UNCLE": "The Man from U.N.C.L.E.",
        "The Seven Percent Solution": "The Seven-Per-Cent Solution",

        # PUBLIC(-ALPHA)  ANIMATION/ANIME
        "in-this-corner-of-the-world": "In this Corner of the World",

        # PUBLIC(-ALPHA)  ANIMATION/BARBIE
        # PUBLIC(-ALPHA)  ANIMATION/DISNEY
        "101 Dalmations": "One Hundred and One Dalmatians",
        "101 Dalmations 2 Patchs London Adventure": "101 Dalmatians 2: Patch's London Adventure",
        "Cinderella 2 Dreams Come True": "Cinderella II: Dreams Come True",
        "Lady and the Tramp II Scamps Adventure": "Lady and the Tramp II: Scamp's Adventure",
        "Lion King 2 Simbas Pride": "Lion King II: Simba's Pride",
        "Oliver and Company": "Oliver & Company",
        "Peter Pan in Return to Neverland": "Return to Neverland",
        "Petes Dragon": "Pete's Dragon",
        "Planes Fire and Rescue": "Planes: Fire & Rescue",
        "Pocahontas II": "Pocahontas 2",
        "Snow White and the Seven Dwarves": "Snow White and the Seven Dwarfs",
        "The Little Mermaid 2 Return to the Sea": "The Little Mermaid II Return to the Sea",
        "Tinkerbell and the Great Fairy Rescue": "Tinker Bell and the Great Fairy Rescue",

        # PUBLIC(-ALPHA)  ANIMATION/UNSORTED
        "Alvin and the Chipmonks": "Alvin and the Chipmunks",
        "Dr Seuss Horton Hears a Who": "Horton Hears a Who",
        "Knut And His Friends": "Knut & Friends",
        "Spider Man Into the Spider Verse": "Spider-Man: Into the Spider-Verse",
        "Surfs Up": "Surf's Up",

        # PUBLIC(-ALPHA)  BIOGRAPHY
        "CS Lewis Beyond Narnia": "C.S. Lewis: Beyond Narnia",
        "Cadallic Records": "Cadillac Records",
        "Charlie Wilsons War": "Charlie Wilson's War",
        "Julie and Julia": "Julie & Julia",
        "Man of Honor": "Men of Honor",
        "The Kings Speech": "The King's Speech",

        # PUBLIC(-ALPHA)  CHRISTIAN
        "Abels Field": "Abel's Field",
        "Amazing Love The Story of Hosea": "Amazing Love",
        "Deadly Choice": "Deadly Choice",
        "Gods not Dead": "God's not Dead",
        "Gods not Dead A Light in Darkness": "God's not Dead: A Light in Darkness",
        "Left Behind 2 Tribulation Force": "Left Behind II: Tribulation Force",
        "Magdalana Released from Shame": "Magdalena: Released from Shame",
        "The Omega Code 2 Megiddo": "Megiddo: The Omega Code 2",
        "Pamelas Prayer": "Pamela's Prayer",
        "Resurrection Trial": "The Prosecutor",
        "Sight and Sound Theatre Jesus": "Jesus",
        "Sight and Sound Theatre Samson": "Samson",
        "Sight and Sount Theatre Ruth": "Sight and Sound Theatre Ruth",

        # PUBLIC(-ALPHA)  CHRISTMAS/HOLIDAY
        "A Childs Christmas in Wales": "A Child's Christmas in Wales",
        "Emmet Otters Jug Band Christmas": "Emmet Otter's Jug-Band Christmas",
        "Ill Be Home for Christmas": "I'll Be Home for Christmas",
        "National Lampoons Christmas Vacation 2 Cousin Eddies Island Adventure":
                "Christmas Vacation 2: Cousin Eddie's Island Adventure",
        "Santa Claus Is Coming to Town": "Santa Claus Is Comin' to Town",
        "The  Santa Clause": "The Santa Clause",
        "The Year Without a Santa Clause": "The Year Without a Santa Claus",
        "Unaccompanies Minors": "Unaccompanied Minors",

        # PUBLIC(-ALPHA)  COMEDY
        "Anaylze That": "Analyze That",
        "Bratz the Movie": "Bratz",
        "Caddyshack 2": "Caddyshack II",
        "Clerks 2": "Clerks II",
        "Critics Choice": "Critic's Choice",
        "Ferris Buellers Day Off": "Ferris Bueller's Day Off",
        "Grandmas Boy": "Grandma's Boy",
        "Legally Blonde 2 Red White and Blonde": "Legally Blonde 2: Red, White and Blonde",
        "Lets Go Collegiate": "Let's Go Collegiate",
        "Madeas Big Happy Family": "Madea's Big Happy Family",
        "Meed Dave": "Meet Dave",
        "Miss Congeniality 2 Armed and Fabalous": "Miss Congeniality 2: Armed & Fabulous",
        "Monster in Law": "Monster-in-Law",
        "Mr Poppers Penguins": "Mr. Popper's Penguins",
        "National Lampoons Animal House": "Animal House",
        "National Lampoons Vacation": "National Lampoon's Vacation",
        "Novacaine": "Novocaine",
        "Nutty Professor 2 The Klumps": "Nutty Professor II: The Klumps",
        "Pall Blart Mall Cop": "Paul Blart Mall Cop",
        "Rich and Strange": "Rich and Strange",
        "Roast Beef and Movies": "Roast-Beef and Movies",
        "Simply Irrestible": "Simply Irresistible",
        "Thats My Boy": "That's My Boy",
        "The Hangover Part 2": "The Hangover Part II",
        "The Royal Tanenbaums": "The Royal Tenenbaums",
        "The Secret Life of Walter Mittig": "The Secret Life of Walter Mitty",
        "The Time Travellers Wife": "The Time Traveler's Wife",
        "You Dont Mess with the Zohan": "You Don't Mess with the Zohan",

        # PUBLIC(-ALPHA)  CRIME
        "Carlitos Way": "Carlito's Way",
        "Carlitos Way Rise to Power": "Carlito's Way Rise to Power",
        "French Connection 2": "French Connection II",
        "Hustle and Flow": "Hustle & Flow",

        "Jasons Lyric": "Jason's Lyric",
        "Oceans Eleven": "Ocean's Eleven",
        "Oceans Thirteen": "Ocean's Thirteen",
        "Oceans Twelve": "Ocean's Twelve",
        "Starsky and Hutch": "Starsky & Hutch",
        "Tango and Cash": "Tango & Cash",
        "The Godfather Part 2": "The Godfather Part II",
        "The Godfather Part 3": "The Godfather Part III",

        # PUBLIC(-ALPHA)  DISNEY/LIVE-ACTION
        "Camprock": "Camp Rock",
        "Disney Descendants 3": "Descendants 3",
        "Pirates of the Caribbean Dead Mans Chest": "Pirates of the Caribbean Dead Man's Chest",
        "Sharpays Fabulous Adventure": "Sharpay's Fabulous Adventure",

        # PUBLIC(-ALPHA)  DRAMA
        "A Sensative Passionate Man": "A Sensitive, Passionate Man",
        "Cheaters Putting the System to the Test": "Cheaters",
        "Divine Secrets of the Ya Ya Sisterhood": "Divine Secrets of the Ya-Ya Sisterhood",
        "Me and You Us Forever": "Me & You, Us, Forever",
        "North County": "North Country",
        "One Flew over the Cuckoos Nest": "One Flew over the Cuckoo's Nest",
        "Sophie and the Moonhanger": "Sophie & the Moonhanger",
        "The Never Ending Story": "The NeverEnding Story",
        "The Never Ending Story 2": "The NeverEnding Story II",
        "We Dont Live Here Anymore": "We Don't Live Here Anymore",

        # PUBLIC(-ALPHA)  FAMILY
        "American Girl Lea to the Resuce": "American Girl: Lea to the Rescue",
        "Beethovens 5th": "Beethoven's 5th",
        "Benjis Very Own Christmas Story": "Benji's Very Own Christmas Story",
        "Bridge to Terabatha": "Bridge to Terabithia",
        "Cats and Dogs": "Cats & Dogs",
        "Charlottes Web": "Charlotte's Web",
        "Hachi A Dogs Tale": "Hachi A Dog's Tale",
        "Harleys Hill": "Harley's Hill",
        "Hollywood Its a Dogs Life": "Hollywood It's a Dog's Life",
        "Its a Wonderful Life": "It's a Wonderful Life",
        "Kid in Africa": "Kid 'in' Africa",
        "Marley and Me": "Marley & Me",
        "Sam Steel and the Jr Detective Agency": "Sam Steele and the Junior Detective Agency",
        "Schools Out": "School's Out",
        "The Butter Cream Gang": "The ButterCream Gang",
        "Waldos Last Stand": "Waldo's Last Stand",
        "Whats to Do": "What's to Do",
        "Willy Wonka and the Chocolate Factory": "Willy Wonka & the Chocolate Factory",

        # PUBLIC(-ALPHA)  FANTASY
        "Alices Adventures in Wonderland": "Alice's Adventures in Wonderland",
        "Blade 2": "Blade II",
        "Ella Enchanged": "Ella Enchanted",
        "Fairy Tale A True Story": "FairyTale: A True Story",
        "Harry Potter and the Half Blood Prince": "Harry Potter and the Half-Blood Prince",
        "Harry Potter and the Sorcerers Stone": "Harry Potter and the Sorcerer's Stone",
        "Hell Boy": "Hellboy",
        "Pans Labrynth": "Pan's Labyrinth",
        "Piercy Jackson and the Olympians The Lightning Thief": "Percy Jackson & the Olympians: The Lightning Thief",
        "The Hobbit Part 1 An Unexpected Journey": "The Hobbit: An Unexpected Journey",
        "The Hobbit Part 2 The Desolation of Smaug": "The Hobbit: The Desolation of Smaug",
        "The Hobbit Part 3 The Battle of the Five Armies": "The Hobbit: The Battle of the Five Armies",
        "The Lord of the Rings The Return of the King Standard Cut": "The Lord of the Rings: The Return of the King",
        "The Sorcerers Apprentice": "The Sorcerer's Apprentice",

        # PUBLIC(-ALPHA)  FOREIGN LANGUAGE
        "Choodon Naa Yaar": "Chhodon Naa Yaar",
        "House of the Flying Daggers": "House of Flying Daggers",
        "IP Man The Legend Is Born": "The Legend Is Born: Ip Man",

        # PUBLIC(-ALPHA)  HISTORY
        "Ben Hur": "Ben-Hur",
        "Honey Dippers": "Honeydripper",
        "Luthor": "Luther",
        "Passchendale": "Passchendaele",
        "Rise to Freedom The Underground Railroad": "Race to Freedom: The Underground Railroad",

        # PUBLIC(-ALPHA)  MUSICAL
        "Bride and Prejudice": "Bride & Prejudice",
        "Dr Horribles Sing Along Blog": "Dr. Horrible's Sing-Along Blog",
        "Dream Girls": "Dreamgirls",
        "Fun in Acupulco": "Fun in Acapulco",
        "GI Blues": "G.I. Blues",
        "Hans Christian Anderson": "Hans Christian Andersen",
        "Maulin Rouge": "Moulin Rouge",
        "Momma Mia": "Mamma Mia",

        # PUBLIC(-ALPHA)  MYSTERY
        "Clue Alternate Endings after end": "Clue",
        "Devils Advocate": "Devil's Advocate",
        "Flight Plan": "Flightplan",
        "Joyride": "Joy Ride",
        "Number Seventeen": "Number 17",
        "Seven": "Se7en",
        "Sherlock Holmes Terror by Night": "Terror by Night",
        "Sherlock Holmes and a Study in Scarlet": "A Study in Scarlet",
        "The Davinci Code": "The Da Vinci Code",
        "The Thirty-Nine Steps": "The 39 Steps",
        "The trail of the Pink Panther": "Trail of the Pink Panther",
        "True Crimes": "True Crime",

        # PUBLIC(-ALPHA)  ROMANCE
        "Benny and Joon": "Benny & Joon",
        "Daddys Little Girls": "Daddy's Little Girls",
        "Deuce Bigalow Male Jigalo": "Deuce Bigalow: Male Gigolo",
        "Diary of a Mad Black Women": "Diary of a Mad Black Woman",
        "Dirty Dancing Havanah Nights": "Dirty Dancing: Havana Nights",
        "Flkipped": "Flipped",
        "Hes Just Not That into You": "He's Just Not That into You",
        "Kate and Leopold": "Kate & Leopold",
        "Le Divorce": "The Divorce",
        "Love and Other Drugs": "Love & Other Drugs",
        "Madeas Family Reunion": "Madea's Family Reunion",
        "Maid in Manhatten": "Maid in Manhattan",
        "My Best Friends Girl": "My Best Friend's Girl",
        "My Moms New Boyfriend": "My Mom's New Boyfriend",
        "PS I Love You": "P.S. I Love You",
        "Paris Je Taime": "Paris Je T'aime",
        "Pride and Prejudice": "Pride & Prejudice",
        "Romeo and Juliet": "Romeo + Juliet",
        "Sex and the City The Movie": "Sex and the City",
        "Sex in the City 2": "Sex and the City 2",
        "Sidways": "Sideways",
        "Somethings Gotta Give": "Something's Gotta Give",
        "St Elmos Fire": "St. Elmo's Fire",
        "The 40 Year Old Virgen": "The 40-Year-Old Virgin",
        "The Break Up": "The Break-Up",
        "The Five Year Engagement": "The Five-Year Engagement",
        "The Heavy": "Heavy",
        "The Importnace of Being Ernest": "The Importance of Being Earnest",
        "The Truth about Cats and Dogs": "The Truth About Cats & Dogs",
        "Tyler Perrys Why Did I Get Married Too": "Why Did I Get Married Too",
        "What to Expect When Youre Expecting": "What to Expect When You're Expecting",
        "Whats Up Doc": "What's Up Doc",
        "Yours Mine and Ours": "Yours, Mine & Ours",
        "Youve Got Mail": "You've Got Mail",

        # PUBLIC(-ALPHA)  SCI(ENCE-)FI(CTION)
        "Atlas Shrugged Part 2": "Atlas Shrugged II: The Strike",
        "Babylon AD": "Babylon A.D.",
        "Back to the Future Part 2": "Back to the Future II",
        "Back To The Future Part 3": "Back to the Future Part III",
        "GI Joe The Rise of Cobra": "G.I. Joe: The Rise of Cobra",
        "Logans War Bound by Honor": "Logan's War Bound by Honor",
        "Men in Black 2": "Men in Black II",
        "Star Trek 2 The Wrath of Kahn": "Star Trek II: The Wrath of Khan",
        "Star Trek 3 The Search for Spock": "Star Trek III: The Search for Spock",
        "Star Trek 4 The Voyage Home": "Star Trek IV: The Voyage Home",
        "Star Trek 5 The Final Frontier": "Star Trek V: The Final Frontier",
        "Star Trek 6 The Undiscovered Country": "Star Trek VI: The Undiscovered Country",
        "Star Wars Episode 1 The Phantom Menace": "Star Wars: Episode I - The Phantom Menace",
        "Star Wars Episode 2 Attack of the Clones": "Star Wars: Episode II - Attack of the Clones",
        "Star Wars Episode 4 A New Hope": "Star Wars: Episode IV - A New Hope",
        "Star Wars Episode 5 The Empire Strikes Back": "Star Wars: Episode V - The Empire Strikes Back",
        "Star Wars Episode 6 Return of the Jedi": "Star Wars: Episode VI - Return of the Jedi",
        "Star Wars Episode 7 The Force Awakens": "Star Wars: Episode VII - The Force Awakens",
        "Star Wars Episode 8 The Last Jedi": "Star Wars: Episode VIII - The Last Jedi",
        "Star Wars Episode 9 The Rise of Skywalker": "Star Wars: Episode IX - The Rise of Skywalker",
        "The Presidents Man": "The President's Man",
        "The Presidents Man A Line in the Sand": "The President's Man: A Line in the Sand",
        "Universal Soldier 2 Brother in Arms": "Universal Soldier II: Brother in Arms",
        "Universal Soldier 3 Unfinished Business": "Universal Soldier III: Unfinished Business",

        # PUBLIC(-ALPHA)  SILENT
        "Aunties Affinity": "Auntie's Affinity",
        "Dads Choice": "Dad's Choice",
        "Good_Morning_Nurse": "Good Morning, Nurse",
        "His Wifes New Lid": "His Wife's New Lid",
        "Pie Eyed": "Pie-Eyed",
        "The Farmers Wife": "The Farmer's Wife",
        "Tillies Punctured Romance": "Tillie's Punctured Romance",
        "Yes Yes Namette": "Yes Yes Nanette",

        # PUBLIC(-ALPHA)  SPORT
        "Its Good to Be Alive": "It's Good to Be Alive",
        "Love and Basketball": "Love & Basketball",
        "Major League 3 Back to the Minors": "Major League: Back to the Minors",
        "Rocky 2": "Rocky II",
        "Rocky 3": "Rocky III",
        "Rocky 4": "Rocky IV",
        "Rocky 5": "Rocky V",

        # PUBLIC(-ALPHA)  SUPERHERO
        "Batman the Movie": "Batman",
        "Batman vs Two Face": "Batman vs. Two-Face",
        "Birdman or the Unexpected Virtue of Ignorance": "Birdman",
        "Captian American Civil War": "Captain America: Civil War",
        "Fantastic 4": "Fantastic Four",
        "Fantastic Four The Rise of the Silver Surfer": "Fantastic Four: Rise of the Silver Surfer",
        "Spiderman": "Spider-Man",
        "Spiderman 2": "Spider-Man 2",
        "Spiderman 3": "Spider-Man 3",
        "Spiderman Homecoming": "Spider-Man: Homecoming",
        "Superman 2": "Superman II",
        "Superman 3": "Superman III",
        "Superman 4 The Quest for Peace": "Superman IV: The Quest for Peace",
        "Superman The Movie": "Superman",
        "The Amazing Spider Man": "The Amazing Spider-Man",
        "Thor Ragnarock": "Thor: Ragnarok",
        "X Men Origins Wolverine": "X-Men Origins: Wolverine",
        "XMen": "X-Men",
        "XMen First Class": "X-Men First Class",
        "XMen The Last Stand": "X-Men The Last Stand",

        # PUBLIC(-ALPHA)  THRILLER
        "13th Child Jersey Devil": "13th Child",
        "Aliens vs Predators Requiem": "Aliens vs. Predator: Requiem",
        "All the Kings Men": "All the King's Men",
        "Backwoods Bloodpath": "Backwoods Bloodbath",
        "Clown Town": "ClownTown",
        "Crime and Punishment in Suburbia": "Crime + Punishment in Suburbia",
        "Hostel Part 2": "Hostel II",
        "Meridan": "Meridian",
        "Nobody Runs Forever": "The High Commissioner",
        "One Eighty Seven": "One Eight Seven",
        "Pandoras Box": "Pandora's Box",
        "Saw 2": "Saw II",
        "Saw 4": "Saw IV",
        "Sororrity Row": "Sorority Row",
        "The Pulse": "Pulse",

        # PUBLIC(-ALPHA)  WAR
        "Black Brigade": "Carter's Army",
        "Casualities of War": "Casualties of War",
        "Harts War": "Hart's War",
        "Hitlers SS A Portrait in Evil": "Hitler's S.S.: Portrait in Evil",
        "Inglorious Basterds": "Inglourious Basterds",
        "MASH": "M*A*S*H",
        "The Cold War Killers": "Cold War Killers",
        "U571": "U-571",
        "Wind Talkers": "Windtalkers",

        # PUBLIC(-ALPHA)  WESTERN
        "Gods Gun": "God's Gun",
        "Helltown": "Hell Town",
        "Kid Vengeance": "Vengeance",
        "Massacre at Fort Holman": "A Reason to Live, a Reason to Die",
        "Sante Fe Stampede": "Santa Fe Stampede",
        "Sante Fe Trail": "Santa Fe Trail",
        "Seven Faces of Dr Lao": "7 Faces of Dr. Lao",
        "The Magnificant Seven": "The Magnificent Seven",
        "The Over the Hill Gang": "The Over-the-Hill Gang",
        "The Over the Hill Gang Rides Again": "The Over-the-Hill Gang Rides Again",
        "The Sagebrush Trail": "Sagebrush Trail",

        # PUBLIC-BRAVO  ACTION
        "Fast and Furious Fast Five": "Fast & Furious 5: Fast Five",
        "GI Joe Retaliation": "G.I. Joe: Retaliation",
        "Prime Target": "Sitting Target",
        "Spooks The Greater Good": "MI-5",
        "Terminator_ Dark Fate": "Terminator: Dark Fate",

        # PUBLIC-BRAVO  ANIMATED
        "Dr Seuss The Lorax": "The Lorax",
        "Minions_ The Rise of Gru": "Minions: The Rise of Gru",
        "Spirit_ Stallion of the Cimarron": "Spirit: Stallion of the Cimarron",
        "The Pilgrim's Progress": "Pilgrim's Progress",

        # PUBLIC-BRAVO  ANIME
        "Hetalia World Series Part 1": "Hetalia Part 1",
        "Hetalia World Series Part 2": "Hetalia Part 2",

        # PUBLIC-BRAVO  CHRISTIAN
        "The Order of Rights": "Order of Rights",

        # PUBLIC-BRAVO  COMEDY
        "Amanda and Jack Go Glamping": "Amanda & Jack Go Glamping",
        "Bill and Teds Bogus Journes": "Bill & Ted's Bogus Journey",
        "Bill and Teds Excellent Adventure": "Bill & Ted's Excellent Adventure",

        # PUBLIC-BRAVO  FAMILY
        "Darby Ogill and the Little People": "Darby O'gill and the Little People",
        "The Gnome Mobile": "The Gnome-Mobile",

        # PUBLIC-BRAVO  FANTASY
        "Highlander 2 The Quickening Renegade Version": "Highlander II: The Quickening",

        # PUBLIC-BRAVO  HOLIDAY(/CHRISTMAS)
        "A Winter Wedding": "A Wedding Wonderland",
        "Christmas Crush": "Holiday High School Reunion",
        "Dolly Parton's Christmas of Many Colors_ Circle of Love":
                "Dolly Parton's Christmas of Many Colors: Circle of Love",
        "Married by Christmas": "The Engagement Clause",

        # PUBLIC-BRAVO  ROMANCE
        "For Love and Honor": "For Love & Honor",
        "The Reality of Love": "I Want to Marry Ryan Banks",

        # PUBLIC-BRAVO  SCI(ENCE)FI(CTION)
        "Invasion Attraction 2": "Invasion",

        # PUBLIC-BRAVO  SILENT
        "What_Price_Glory": "What Price Glory",

        # PUBLIC-BRAVO  THRILLER
        "9_11": "9/11",
        "Gremlins 2_ The New Batch": "Gremlins 2: The New Batch",

        # PUBLIC-CHARLIE
        "50 50": "50/50",
        "A Kid in King Arthurs Court": "A Kid in King Arthur's Court",
        "A Midsummer Nights Dream": "A Midsummer Night's Dream",
        "A Nightmare on Elm Street 2 Freddies Revenge": "Nightmare on Elm Street 2",
        "A Team": "A-Team",
        "African Screams": "Africa Screams",
        "Airplane II_ The Sequel": "Airplane II: The Sequel",
        "Alan and Naomi": "Alan Naomi",
        "Alien 3": "Alien³",
        "Alita_ Battle Angel": "Alita: Battle Angel",
        "Avengers Grimm_ Time Wars": "Avengers Grimm: Time Wars",
        "Bar Z Bad Men": "Bar-Z Bad Men",
        "Because of Winn Dixie": "Because of Winn-Dixie",
        "Brainiacs Dot Com": "The Brainiacs.com",
        "Brothehood of Justice": "The Brotherhood of Justice",
        "Bubba Hotep": "Bubba Ho-tep",
        "Call of the Wild A Race for Buck": "Call of the Wild",
        "Castaway": "Cast Away",
        "Catch 22": "Catch-22",
        "Confessions of a Shopholic": "Confessions of a Shopaholic",
        "Curious George_ Cape Ahoy": "Curious George: Cape Ahoy",
        "Danielle Steels Daddy": "Daddy",
        "Dispicable Me": "Despicable Me",
        "Disneys Princess and the Frog": "The Princess and the Frog",
        "Dragonball_ Evolution": "Dragonball Evolution",
        "Dragonheart 3_ The Sorcerer's Curse": "Dragonheart 3: The Sorcerer's Curse",
        "Dragonheart_ A New Beginning": "Dragonheart: A New Beginning",
        "Dragonheart_ Battle for the Heartfire": "Dragonheart: Battle for the Heartfire",
        "Earnest Goes to Africa": "Ernest Goes to Africa",
        "Earnest Goes to School": "Ernest Goes to School",
        "Escape Plan 2_ Hades": "Escape Plan 2: Hades",
        "F9_ The Fast Saga": "Fast & Furious 9: F9: The Fast Saga",
        "Fair Play": "Fairplay",
        "Fantastic Beasts_ The Secrets of Dumbledore": "Fantastic Beasts: The Secrets of Dumbledore",
        "Fast and Furious": "Fast & Furious 4: Fast & Furious",
        "Fielders Choice": "Fielder's Choice",
        "Flower Shop Mystery_ Mum's the Word": "Flower Shop Mystery: Mum's the Word",
        "GForce": "G-Force",
        "Geromino": "Geronimo",
        "Gromits Tail Waggin DVD": "Gromit's Tail-Waggin DVD",
        "Gunfight at the OK Corral": "Gunfight at the O.K. Corral",
        "Gunther and the Paper Brigade": "The Paper Brigade",
        "Happily Never After": "Happily N'Ever After",
        "Hey Vern Its My Family Album": "Hey Vern It's My Family Album",
        "I Now Pronounce You Chuck and Larry": "I Now Pronounce You Chuck & Larry",
        "In Harms Way": "In Harm's Way",
        "In a Strangers Hand": "And then she was gone",
        "Jacobs Harvest": "Jacob's Harvest",
        "Jawbreakers": "Jawbreaker",
        "John Wick_ Chapter 4": "John Wick: Chapter 4",
        "Justice Society_ World War II": "Justice Society: World War II",
        "KPax": "K-Pax",
        "Karen Kingsbury's The Bridge Part 2": "The Bridge Part 2",
        "Land Before Time 11 Invasion of the Tinysauruses": "Land Before Time XI Invasion of the Tinysauruses",
        "Lara Croft Tomb Raider_ The Cradle of Life": "Lara Croft: Tomb Raider - The Cradle of Life",
        "Leap Frog Talking Words Factory": "Talking Words Factory",
        "Lego The Phantom Padawan": "Lego Padawan Menace",
        "Let There Be Light": "Let There Be Light",
        "Lifes Abiding Joy": "Love's Abiding Joy",
        "Lilo and Stich": "Lilo & Stitch",
        "Lion King One and a Half": "The Lion King 1½",
        "Live from Lincoln Center_ Rodgers and Hammerstein's Carousel": "Rodger and Hammerstein's Carousel",
        "Long John Silvers Return to Treasure Island": "Long John Silver's Return to Treasure Island",
        "Love is a Many Splendored Thing": "Love is a Many-Splendored Thing",
        "Madeas Class Reunion": "Madea's Class Reunion",
        "Mannequin Two_ On the Move": "Mannequin 2: On the Move",
        "Max Lucado You Are Special": "You Are Special",
        "Maze Runner_ The Death Cure": "Maze Runner: The Death Cure",
        "Mee Shee The Water Giant": "Mee-Shee The Water Giant",
        "Men In Black_ International": "Men In Black: International",
        "Mickeys Twice upon a Christmas": "Mickey's Twice upon a Christmas",
        "Miss Peregrines Home for Unfortunate Children": "Miss Peregrine's Home for Peculiar Children",
        "Mission_ Impossible": "Mission: Impossible",
        "Mister Atlas": "Mr Atlas",
        "Monsters Ball": "Monster's Ball",
        "Morning Show Mysteries_ A Murder in Mind": "Morning Show Mysteries: A Murder in Mind",
        "Morning Show Mysteries_ Countdown to Murder": "Morning Show Mysteries: Countdown to Murder",
        "Mother_Android": "Mother/Android",
        "My Babys Daddy": "My Baby's Daddy",
        "My Sisters Keeper": "My Sister's Keeper",
        "Mystery of  Her": "Mystery of Her",
        "National Lampoons Christmas Vacation": "National Lampoon's Christmas Vacation",
        "New Years Eve": "New Year's Eve",
        "Oceans 8": "Ocean's Eight",
        "On Our Way": "On Our Way",
        "Pegasus_ Pony with a Broken Wing": "Pegasus: Pony with a Broken Wing",
        "Pilgrims Progress Journey to Heaven": "Pilgrim's Progress",
        "Rapture Palooza": "Rapture-Palooza",
        "Roundup Time in Texas": "Round-up Time in Texas",
        "Schindlers List": "Schindler's List",
        "Shes Out of My League": "She's Out of My League",
        "Shirley Temple's Storybook_ Pippi Longstocking": "Pippi Longstocking",
        "Sinbad_ Legend of the Seven Seas": "Sinbad: Legend of the Seven Seas",
        "Skin Walkers": "Skinwalkers",
        "Sleepy Hallow": "Sleepy Hollow",
        "Sniper_ Special Ops": "Sniper: Special Ops",
        "Space Jam_ A New Legacy": "Space Jam: A New Legacy",
        "Star Trek_ Insurrection": "Star Trek: Insurrection",
        "Star Trek_ Nemesis": "Star Trek: Nemesis",
        "Star Wars 3 Revenge of the Sith": "Star Wars Revenge of the Sith",
        "Star Wars Rogue One": "Rogue One Star Wars",
        "Taken 2 Uncut": "Taken 2",
        "Tarzan II": "Tarzan 2",
        "Tarzan and the Green Goddess": "The New Adventures of Tarzan",
        "Tarzans Revenge": "Tarzan's Revenge",
        "Team America_ World Police": "Team America: World Police",
        "The Adventures of Gallant Bess": "Adventures of Gallant Bess",
        "The Baby Sitters Club": "The Baby-Sitters Club",
        "The Bishops Wife": "The Bishop's Wife",
        "The Cavemans Valentine": "The Caveman's Valentine",
        "The Craft_ Legacy": "The Craft: Legacy",
        "The Fighting Westerner": "The Fighting Westerner",
        "The Flinstones": "The Flintstones",
        "The Guns of Navaronne": "The Guns of Navarone",
        "The Hitchhikers Guide to the Galaxy": "The Hitchhiker's Guide to the Galaxy",
        "The Land Before Time 1": "The Land Before Time",
        "The Land Before Time 2 The Great Valley Adventure": "The Land Before Time ii The Great Valley Adventure",
        "The Land before Time 4 Journey through the Mists": "The Land before Time iv Journey through the Mists",
        "The Last Sentinel": "Last Sentinel",
        "The Legend of Cougar Canyon": "Legend of Cougar Canyon",
        "The Miracle Maker The Story of Jesus": "The Miracle Maker",
        "The Out-of-Towners": "The Out of Towners",
        "The Presidents Plane is Missing": "The President's Plane is Missing",
        "The Three Muskteers": "The Three Musketeers",
        "The Weatherman": "The Weather Man",
        "Top Gun_ Maverick": "Top Gun: Maverick",
        "Trust Thomas and Other Stories": "Thomas Friends Trust Stories",
        "The Twilight Saga_ Breaking Dawn_ Part 2": "The Twilight Saga: Breaking Dawn - Part 2",
        "US Marshals": "U.S. Marshals",
        "Under California Skies": "Under California Stars",
        "Underworld_ Awakening": "Underworld: Awakening",
        "Valentines Day": "Valentine's Day",
        "Wall E": "WALL·E",
        "Wallace & Gromit_ The Curse of the Were-Rabbit": "The Curse of the Were-Rabbit",
        "Where the Red Fern Grows II": "Where the Red Fern Grows: Part Two",
        "Winnie the Pooh and Christmas Too": "Winnie the Pooh & Christmas Too",

        # OTHER
        "Bridal Bootcamp": "Bridal Boot Camp",
        "Second Hand Lions": "Secondhand Lions",
}

MOVIE_KEYS = SPECIAL_MOVIE_NAMES.keys()
